version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        DB_URL: postgresql://postgres:password@pg:5432/dev-directory
    ports:
      - 3000:3000
