version: "3.9"

services:
  app:
    build: .
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: dev-directory
      DB_LOGGING: false
    container_name: dev-directory-app
    ports:
      - 3000:3000
