version: "3.9"

services:
  app:
    build:
        context: .
        args:
          DB_HOST: dev-directory_pg_1
          DB_PORT: 5432
          DB_USER: postgres
          DB_NAME: dev-directory
          DB_PASSWORD: password
    ports:
      - 3000:3000


