version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        DB_PASSWORD: password
        DB_HOST: pg
        DB_PORT: 5432
        DB_USER: postgres
        DB_NAME: dev-directory
    ports:
      - 3000:3000
